// Single source of truth for every reserved dsh-* name in this monorepo.
// Ported from ~/workspace/dsh-reserved/generate.py - keep in sync here from now on.
//
// headline  -> package.json description prefix / README headline
// body      -> README paragraph describing the planned first release
// extra     -> extra npm keywords beyond the standard dsh set
// niche     -> grouping used by the root README and the check script

import { EXTERNAL } from './catalog-external.mjs'

export const REPO = {
  owner: 'dushaobindoudou',
  repo: 'dsh-plugin',
  get url() {
    return `https://github.com/${this.owner}/${this.repo}`
  },
}

export const NICHE_ORDER = [
  'model bridges',
  'developer tools',
  'agent capabilities',
  'channels',
  'web3 & payments',
  'multi-agent',
  'role presets',
  'interaction',
  'evaluation',
  'protocols',
  'ui',
  'data',
  'ops',
  'security',
  'work & hiring',
  'meta / product',
  'harness surfaces',
  'external waves',
]

export const CORE = {
  // ---- model bridges ----------------------------------------------------
  'dsh-google': {
    niche: 'model bridges',
    headline: 'Google services umbrella bridge',
    body: 'The company-form seat above dsh-gemini and dsh-vertex - Search Console, Ads, and Workspace surfaces exposed as dsh providers for go-global work.',
    extra: ['google', 'bridge'],
  },
  'dsh-deepseek': {
    niche: 'model bridges',
    headline: 'DeepSeek model bridge',
    body: 'DeepSeek API models as first-class dsh providers - the native brand seat, kept in-family so no third party can squat between the harness and its own model vendor.',
    extra: ['deepseek', 'bridge'],
  },
  'dsh-mixtral': {
    niche: 'model bridges',
    headline: 'Mixtral model bridge',
    body: 'The Mistral Mixtral mixture-of-experts models as dsh providers - sparse routing surfaced as per-turn token accounting.',
    extra: ['mixtral', 'moe'],
  },
  'dsh-anthropic': {
    niche: 'model bridges',
    headline: 'Anthropic API bridge',
    body: 'The company-form companion to dsh-claude - direct Anthropic API endpoints as dsh providers, for setups that authenticate per organization rather than per model family.',
    extra: ['anthropic'],
  },
  'dsh-huggingface': {
    niche: 'model bridges',
    headline: 'Hugging Face model bridge',
    body: 'Inference Endpoints and the Serverless API as dsh providers - any HF-hosted model one environment variable away.',
    extra: ['huggingface', 'inference'],
  },
  'dsh-hf': {
    niche: 'model bridges',
    headline: 'The short form of the Hugging Face bridge',
    body: 'Compatibility name: the Hugging Face bridge ships as dsh-huggingface; this form keeps the community-standard short spelling installable.',
    extra: ['hf', 'huggingface'],
  },
  'dsh-vertex': {
    niche: 'model bridges',
    headline: 'Google Vertex AI bridge',
    body: 'Vertex AI endpoints as dsh providers - enterprise GCP auth, quota-aware routing surfaced per turn.',
    extra: ['vertex', 'gcp'],
  },
  'dsh-yi': {
    niche: 'model bridges',
    headline: 'Yi model bridge',
    body: '01.AI Yi models as dsh providers - bilingual long-context strength surfaced in the budget line.',
    extra: ['yi', '01ai'],
  },
  'dsh-step': {
    niche: 'model bridges',
    headline: 'StepFun model bridge',
    body: 'StepFun Step models as dsh providers - Chinese-market strength with per-turn pricing.',
    extra: ['stepfun', 'step'],
  },
  'dsh-sonar': {
    niche: 'model bridges',
    headline: 'Sonar model bridge',
    body: 'Perplexity Sonar models as dsh providers - the search-grounded family behind dsh-perplexity, available model-by-model.',
    extra: ['sonar', 'perplexity'],
  },
  'dsh-ollama': {
    niche: 'model bridges',
    headline: 'Ollama model bridge',
    body: 'Local models as dsh providers - the Ollama catalog exposed through the LLM adapter seam, zero egress by default. Registered externally; promoted into the curated core.',
    extra: ['ollama', 'local', 'llama'],
  },
  'dsh-openrouter': {
    niche: 'model bridges',
    headline: 'OpenRouter model bridge',
    body: 'Every OpenRouter model as a dsh provider - one key, hundreds of models, routing decisions and pricing surfaced per turn. Registered externally; promoted into the curated core.',
    extra: ['openrouter', 'routing', 'bridge'],
  },
  'dsh-mistral': {
    niche: 'model bridges',
    headline: 'Mistral model bridge',
    body: 'Mistral endpoints as dsh providers - open-weight European models with per-turn pricing. Registered externally; promoted into the curated core.',
    extra: ['mistral', 'bridge'],
  },
  'dsh-cohere': {
    niche: 'model bridges',
    headline: 'Cohere model bridge',
    body: 'Cohere endpoints as dsh providers - Command R and rerank surfaces exposed for retrieval-heavy work. Registered externally; promoted into the curated core.',
    extra: ['cohere', 'rag'],
  },
  'dsh-groq': {
    niche: 'model bridges',
    headline: 'Groq model bridge',
    body: 'Groq LPU speed for open models as dsh providers - tokens/second surfaced in the metrics line. Registered externally; promoted into the curated core.',
    extra: ['groq', 'fast', 'bridge'],
  },
  'dsh-vllm': {
    niche: 'model bridges',
    headline: 'vLLM model bridge',
    body: 'Self-hosted vLLM serving as a dsh provider - your GPUs, your endpoints, batch throughput surfaced. Registered externally; promoted into the curated core.',
    extra: ['vllm', 'self-hosted', 'gpu'],
  },
  'dsh-together': {
    niche: 'model bridges',
    headline: 'Together AI model bridge',
    body: 'Together endpoints as dsh providers - open-model serving with per-turn pricing. Registered externally; promoted into the curated core.',
    extra: ['together', 'bridge'],
  },
  'dsh-lmstudio': {
    niche: 'model bridges',
    headline: 'LM Studio model bridge',
    body: "LM Studio's local server as a dsh provider - desktop-class local models, no egress. Registered externally; promoted into the curated core.",
    extra: ['lmstudio', 'local'],
  },
  'dsh-glm': {
    niche: 'model bridges',
    headline: 'GLM model bridge',
    body: 'Zhipu GLM models as dsh providers - bilingual strength and agentic tool use surfaced per turn. Registered externally; promoted into the curated core.',
    extra: ['glm', 'zhipu'],
  },
  'dsh-doubao': {
    niche: 'model bridges',
    headline: 'Doubao model bridge',
    body: 'ByteDance Doubao models as dsh providers - Volcano endpoints, pricing per turn. Registered externally; promoted into the curated core.',
    extra: ['doubao', 'bytedance'],
  },
  'dsh-minimax': {
    niche: 'model bridges',
    headline: 'MiniMax model bridge',
    body: 'MiniMax models as dsh providers - long-context strength surfaced in the budget line. Registered externally; promoted into the curated core.',
    extra: ['minimax', 'bridge'],
  },
  'dsh-baichuan': {
    niche: 'model bridges',
    headline: 'Baichuan model bridge',
    body: 'Baichuan models as dsh providers through the LLM adapter seam - Chinese-language strength, pricing surfaced per turn.',
    extra: ['baichuan', 'llm', 'bridge'],
  },
  'dsh-perplexity': {
    niche: 'model bridges',
    headline: 'Perplexity bridge for sourced answers',
    body: 'Routes questions through Sonar endpoints - answers arrive with citations, mapped into the harness citation surface; the search-grounded provider.',
    extra: ['perplexity', 'search', 'citations'],
  },
  'dsh-claude': {
    niche: 'model bridges',
    headline: 'Anthropic Claude provider bridge for the DeepSeek Harness',
    body: 'Registers Claude models as dsh providers through the LLM adapter seam - extended thinking streamed as reasoning chunks, prompt-caching savings reported per turn.',
    extra: ['anthropic', 'claude'],
  },
  'dsh-openai': {
    niche: 'model bridges',
    headline: 'OpenAI provider bridge for the DeepSeek Harness',
    body: 'GPT models over the Responses API, keyed from OPENAI_API_KEY through the standard credentials path - no settings.yaml editing.',
    extra: ['openai'],
  },
  'dsh-gpt': {
    niche: 'model bridges',
    headline: 'The GPT-family spelled form of the OpenAI bridge',
    body: 'Compatibility name: the OpenAI bridge ships as dsh-openai; this form keeps the model-family spelling installable.',
    extra: ['openai', 'gpt'],
  },
  'dsh-gemini': {
    niche: 'model bridges',
    headline: 'Google Gemini provider bridge for the DeepSeek Harness',
    body: 'Native multimodal Gemini access - images in, text out - with thinking budgets surfaced as per-model options.',
    extra: ['gemini', 'google'],
  },
  'dsh-qwen': {
    niche: 'model bridges',
    headline: 'Qwen provider bridge for the DeepSeek Harness',
    body: 'DashScope-served Qwen models as dsh providers, with context-length awareness in the model chip and coder variants preconfigured.',
    extra: ['qwen', 'dashscope'],
  },
  'dsh-glm': {
    niche: 'model bridges',
    headline: 'GLM provider bridge for the DeepSeek Harness',
    body: 'Zhipu GLM series via the open-platform API - reasoning models streamed as thought chunks, web-search variants flagged in the model list.',
    extra: ['glm', 'zhipu'],
  },
  'dsh-kimi': {
    niche: 'model bridges',
    headline: 'Kimi provider bridge for the DeepSeek Harness',
    body: 'Moonshot Kimi models as dsh providers - long-context variants surfaced with their true context windows.',
    extra: ['kimi', 'moonshot'],
  },
  'dsh-doubao': {
    niche: 'model bridges',
    headline: 'Doubao provider bridge for the DeepSeek Harness',
    body: 'Volcengine Ark-served Doubao models as dsh providers, endpoint IDs resolvable by display name.',
    extra: ['doubao', 'volcengine'],
  },
  'dsh-minimax': {
    niche: 'model bridges',
    headline: 'MiniMax provider bridge for the DeepSeek Harness',
    body: 'MiniMax models as dsh providers through the same adapter seam the other bridges use.',
    extra: ['minimax'],
  },
  'dsh-mistral': {
    niche: 'model bridges',
    headline: 'Mistral provider bridge for the DeepSeek Harness',
    body: 'Mistral and Codestral models as dsh providers - Codestral preconfigured for edit-heavy workflows.',
    extra: ['mistral', 'codestral'],
  },
  'dsh-groq': {
    niche: 'model bridges',
    headline: 'Groq provider bridge for the DeepSeek Harness',
    body: 'LPU-fast inference behind the standard seam - time-to-first-token shown live in the session header.',
    extra: ['groq'],
  },
  'dsh-together': {
    niche: 'model bridges',
    headline: 'Together AI provider bridge for the DeepSeek Harness',
    body: 'Open-weight models on demand as dsh providers, with per-model pricing surfaced at selection time.',
    extra: ['together'],
  },
  'dsh-fireworks': {
    niche: 'model bridges',
    headline: 'Fireworks AI provider bridge for the DeepSeek Harness',
    body: 'Fast open-model serving as dsh providers, Fireworks model IDs mapped to friendly names.',
    extra: ['fireworks'],
  },
  'dsh-siliconflow': {
    niche: 'model bridges',
    headline: 'SiliconFlow provider bridge for the DeepSeek Harness',
    body: 'Aggregated open-model serving on SiliconFlow as dsh providers - one key, the whole Chinese open-model catalog.',
    extra: ['siliconflow'],
  },
  'dsh-zhipu': {
    niche: 'model bridges',
    headline: 'The company-spelled form of the GLM provider bridge',
    body: 'Compatibility name: the Zhipu GLM bridge ships as dsh-glm; this form keeps the company spelling installable.',
    extra: ['zhipu', 'glm'],
  },
  'dsh-xai': {
    niche: 'model bridges',
    headline: 'xAI Grok provider bridge for the DeepSeek Harness',
    body: 'Grok models as dsh providers through the LLM adapter seam - agent-mode tool loops streamed turn by turn, DeepSearch runs surfaced as cited session evidence. Company-spelled form; the grok-spelled community package exists separately.',
    extra: ['xai', 'grok'],
  },
  'dsh-moonshot': {
    niche: 'model bridges',
    headline: 'The company-spelled form of the Kimi provider bridge',
    body: 'Compatibility name: the Kimi bridge ships as dsh-kimi; this form keeps the Moonshot AI company spelling installable.',
    extra: ['moonshot', 'kimi'],
  },
  'dsh-hunyuan': {
    niche: 'model bridges',
    headline: 'Tencent Hunyuan provider bridge for the DeepSeek Harness',
    body: 'Hunyuan models as dsh providers through the LLM adapter seam, with the hybrid thinking modes surfaced as per-model options.',
    extra: ['hunyuan', 'tencent'],
  },
  'dsh-ernie': {
    niche: 'model bridges',
    headline: 'Baidu ERNIE provider bridge for the DeepSeek Harness',
    body: 'ERNIE models via the Qianfan API as dsh providers - the Baidu arm of the provider bridge family.',
    extra: ['ernie', 'baidu', 'qianfan'],
  },
  'dsh-vllm': {
    niche: 'model bridges',
    headline: 'vLLM provider bridge for the DeepSeek Harness',
    body: 'Point dsh at a self-hosted vLLM server - OpenAI-compatible endpoints auto-probed, served models listed as first-class providers.',
    extra: ['vllm', 'self-hosted'],
  },
  'dsh-llama': {
    niche: 'model bridges',
    headline: 'Llama provider bridge for the DeepSeek Harness',
    body: "Meta's Llama family wherever you serve it - local or hosted - registered as dsh providers from one config block.",
    extra: ['llama', 'meta'],
  },
  'dsh-cohere': {
    niche: 'model bridges',
    headline: 'Cohere provider bridge for the DeepSeek Harness',
    body: 'Command models as dsh providers, with Rerank exposed as a retrieval tool for RAG flows.',
    extra: ['cohere'],
  },
  'dsh-bedrock': {
    niche: 'model bridges',
    headline: 'AWS Bedrock provider bridge for the DeepSeek Harness',
    body: 'IAM-authenticated model access - no static API keys in settings.yaml, roles assumed through the ambient credential chain.',
    extra: ['bedrock', 'aws'],
  },
  'dsh-ollama': {
    niche: 'model bridges',
    headline: 'Local-model provider bridge for the DeepSeek Harness',
    body: 'Registers Ollama-served models as dsh providers through the LLM adapter seam, auto-discovers installed models, and surfaces context-length limits in the model chip.',
    extra: ['ollama'],
  },
  'dsh-openrouter': {
    niche: 'model bridges',
    headline: 'OpenRouter provider bridge for the DeepSeek Harness',
    body: "One provider, the whole model catalog - routed through OpenRouter with per-model cost and rate-limit headers surfaced into dsh's model selection UI.",
    extra: ['openrouter'],
  },
  'dsh-lmstudio': {
    niche: 'model bridges',
    headline: 'LM Studio provider bridge for the DeepSeek Harness',
    body: 'Connects a local LM Studio server as a dsh provider; keeps the model list in sync with what LM Studio currently has loaded.',
    extra: ['lm-studio'],
  },
  'dsh-proxy': {
    niche: 'model bridges',
    headline: 'LLM gateway plugin for the DeepSeek Harness',
    body: 'Routes dsh model calls through a local proxy - request logging, header rewriting, fallback chains, and multi-key rotation - without touching settings.yaml.',
    extra: ['proxy', 'gateway'],
  },
  'dsh-models': {
    niche: 'model bridges',
    headline: 'Model registry panel for the DeepSeek Harness',
    body: 'Every registered model in one table - context windows, pricing, thinking modes, and which provider serves it; pin defaults per profile.',
    extra: ['models', 'registry'],
  },
  'dsh-providers': {
    niche: 'model bridges',
    headline: 'Provider registry for the DeepSeek Harness',
    body: 'The other half of the model table - credential status, rate limits, latency, and fallback order for every LLM adapter, live.',
    extra: ['providers', 'llm', 'registry'],
  },
  // ---- developer tools --------------------------------------------------
  'dsh-vercel': {
    niche: 'developer tools',
    headline: 'Vercel bridge for dsh agents',
    body: 'Deploy previews as first-class artifacts - the agent proposes, the preview builds, you approve the promotion to production.',
    extra: ['vercel', 'deploy'],
  },
  'dsh-cloudflare': {
    niche: 'developer tools',
    headline: 'Cloudflare bridge for dsh agents',
    body: 'Workers, DNS, and WAF as agent surfaces - draft changes, see the diff, approve; the audit log stays on the Cloudflare side.',
    extra: ['cloudflare', 'edge'],
  },
  'dsh-netlify': {
    niche: 'developer tools',
    headline: 'Netlify bridge for dsh agents',
    body: 'Deploy hooks and form submissions routed into sessions - build failures triaged by the agent with the log tail attached.',
    extra: ['netlify', 'deploy'],
  },
  'dsh-zapier': {
    niche: 'developer tools',
    headline: 'Zapier bridge for dsh agents',
    body: 'Five thousand apps, one seam - the agent drafts zaps and fires webhooks; dsh becomes a step in every automation you already run.',
    extra: ['zapier', 'automation'],
  },
  'dsh-n8n': {
    niche: 'developer tools',
    headline: 'n8n bridge for dsh agents',
    body: 'Self-hosted automation glue - trigger dsh runs from n8n workflows and call n8n webhooks from bots; the two-way bridge for private stacks.',
    extra: ['n8n', 'automation'],
  },
  'dsh-gitlab': {
    niche: 'developer tools',
    headline: 'GitLab bridge for dsh agents',
    body: 'Issues, MRs, and pipelines as agent surfaces - draft MR descriptions, triage failing pipelines, and link sessions to issues; the self-hosted GitHub. Registered externally; promoted into the curated core.',
    extra: ['gitlab'],
  },
  'dsh-neovim': {
    niche: 'developer tools',
    headline: 'Neovim bridge',
    body: 'Drive dsh sessions from Neovim - buffer as context, diffs applied via inline signs; the modal-editing seam beside dsh-zed and dsh-cursor.',
    extra: ['neovim', 'vim'],
  },
  'dsh-emacs': {
    niche: 'developer tools',
    headline: 'Emacs bridge',
    body: 'Run dsh from Emacs - region as context, org-mode integration for run notes; the old-school seam, M-x dsh.',
    extra: ['emacs'],
  },
  'dsh-jetbrains': {
    niche: 'developer tools',
    headline: 'JetBrains IDE bridge',
    body: 'Run dsh from IntelliJ, PyCharm, WebStorm, and friends - project-aware context, diffs applied in the editor gutter.',
    extra: ['jetbrains', 'intellij'],
  },
  'dsh-helix': {
    niche: 'developer tools',
    headline: 'Helix editor bridge',
    body: 'Drive dsh sessions from Helix - selection as context, inline diffs; the modal-native modern seam.',
    extra: ['helix'],
  },
  'dsh-warp': {
    niche: 'developer tools',
    headline: 'Warp terminal bridge',
    body: 'Run dsh inside Warp blocks - output captured per block, AI-native terminal meets agent-native harness.',
    extra: ['warp', 'terminal'],
  },
  'dsh-commit': {
    niche: 'developer tools',
    headline: 'Commit workflow for dsh agents',
    body: 'Staged diffs in, conventional-commit messages out - the agent drafts from the actual diff, you approve; hooks into the approval seam.',
    extra: ['commit', 'git'],
  },
  'dsh-windsurf': {
    niche: 'developer tools',
    headline: 'Windsurf IDE bridge',
    body: 'Run dsh sessions from the Windsurf editor - selection as context, diffs applied in place; the IDE seam beside dsh-cursor and dsh-zed.',
    extra: ['windsurf', 'ide', 'editor'],
  },
  'dsh-tmux': {
    niche: 'developer tools',
    headline: 'tmux surface for dsh',
    body: 'Panes as sessions - spawn a bot per pane, live status in the status bar, pane titles as presence; terminal-native parallelism for dsh-bot fleets.',
    extra: ['tmux', 'terminal', 'multiplexer'],
  },
  'dsh-edit': {
    niche: 'developer tools',
    headline: 'Inline edit panel for the dsh web GUI',
    body: 'Propose file edits in place - hunk-by-hunk approval, reject-and-revise on the spot, everything through the approval seam.',
    extra: [],
  },
  'dsh-refactor': {
    niche: 'developer tools',
    headline: 'Refactor workflows for the dsh web GUI',
    body: 'Symbol renames and moves previewed as one whole-change diff before anything writes - multi-file, reviewable, reversible.',
    extra: ['refactor'],
  },
  'dsh-lint': {
    niche: 'developer tools',
    headline: 'Lint findings inline in the dsh web GUI',
    body: 'Problem list with severity chips and jump-to-line, wired into the file manager and the turn review.',
    extra: ['linter'],
  },
  'dsh-test': {
    niche: 'developer tools',
    headline: 'Test runner panel for the dsh web GUI',
    body: 'Run suites, watch mode, and failure output attached to the turn that caused it - rerun one test with one click.',
    extra: ['testing'],
  },
  'dsh-debug': {
    niche: 'developer tools',
    headline: 'Debug console for dsh agents',
    body: 'Step through tool calls, inspect payloads, and replay a turn from any node - the agent loop made observable.',
    extra: ['debugger'],
  },
  'dsh-db': {
    niche: 'developer tools',
    headline: 'Database client tools for dsh agents',
    body: 'Query, inspect schema, and edit rows through the approval seam - read paths free, writes gated.',
    extra: ['database', 'sql'],
  },
  'dsh-api': {
    niche: 'developer tools',
    headline: 'REST client panel for the dsh web GUI',
    body: 'Requests saved as workspace files, replayable from any session; responses attach to the conversation as evidence.',
    extra: ['rest', 'http'],
  },
  'dsh-git': {
    niche: 'developer tools',
    headline: 'Git panel for the dsh web GUI',
    body: 'Branch, status, stage, commit, and diff surfaces in the web GUI, built on the shell seam (ctx.shell). Complements per-session branch selectors with a whole-repo view.',
    extra: ['git'],
  },
  // ---- agent capabilities -----------------------------------------------
  'dsh-qq': {
    niche: 'channels',
    headline: 'QQ channel bridge for dsh bots',
    body: 'Bots in QQ groups and channels - outbound digests and inbound commands over the QQ bot API; the Chinese-messaging lane beside dsh-x.',
    extra: ['qq', 'channel'],
  },
  'dsh-douyin': {
    niche: 'channels',
    headline: 'Douyin bridge for dsh bots',
    body: 'Publish run outputs as Douyin drafts - text-to-video summaries composed from runs.jsonl, approved before posting.',
    extra: ['douyin', 'channel'],
  },
  'dsh-xiaohongshu': {
    niche: 'channels',
    headline: 'Xiaohongshu bridge for dsh bots',
    body: 'Post agent-written notes and digests to Xiaohongshu - marketing content drafted from run summaries, human-approved.',
    extra: ['xiaohongshu', 'channel'],
  },
  'dsh-bilibili': {
    niche: 'channels',
    headline: 'Bilibili bridge for dsh bots',
    body: 'Turn session replays and digests into Bilibili draft videos - title, cover, and script drafted by the agent.',
    extra: ['bilibili', 'channel'],
  },
  'dsh-agents': {
    niche: 'agent capabilities',
    headline: 'Agent registry panel for the dsh web GUI',
    body: 'Browse, compare, fork, and pin agent presets - what each preset changes, in plain rows, before you switch.',
    extra: [],
  },
  'dsh-planner': {
    niche: 'agent capabilities',
    headline: 'Plan mode for dsh sessions',
    body: 'Editable task trees the agent proposes and you approve - the plan stays visible, checkpoints rollback-able.',
    extra: ['planning'],
  },
  'dsh-rag': {
    niche: 'agent capabilities',
    headline: 'Retrieval-augmented answers over workspace docs',
    body: 'Local index, cited chunks, no external service - answers quote the file and line they came from.',
    extra: ['rag', 'retrieval'],
  },
  'dsh-embeddings': {
    niche: 'agent capabilities',
    headline: 'Embeddings service panel for the DeepSeek Harness',
    body: 'Index, dedupe, and inspect vectors for any local collection - the storage seam with a face.',
    extra: ['embeddings', 'vectors'],
  },
  'dsh-router': {
    niche: 'agent capabilities',
    headline: 'Model router for the DeepSeek Harness',
    body: 'Per-task routing rules - cheap models draft, strong models finish - without editing profiles or restarting.',
    extra: ['router', 'routing'],
  },
  'dsh-search': {
    niche: 'agent capabilities',
    headline: 'Cross-session full-text search for the DeepSeek Harness',
    body: 'Ripgrep over sessions, memory, and the workspace in one query; results jump straight to the conversation node that produced them.',
    extra: ['search'],
  },
  'dsh-deepsearch': {
    niche: 'agent capabilities',
    headline: 'Agentic web research for dsh sessions',
    body: 'The DeepSearch pattern as a harness surface - multi-hop web research with citations, run as a session mode rather than one tool call; every claim links to its source.',
    extra: ['deepsearch', 'research', 'web-search'],
  },
  // ---- multi-agent -------------------------------------------------------
    // ---- web3 & payments --------------------------------------------------
  'dsh-sol': {
    niche: 'web3 & payments',
    headline: 'The short form of the Solana bridge',
    body: 'Compatibility name: the Solana bridge ships as dsh-solana; this form keeps the ticker spelling installable.',
    extra: ['sol', 'solana'],
  },
  'dsh-polygon': {
    niche: 'web3 & payments',
    headline: 'Polygon bridge for dsh agents',
    body: 'PoS chain reads - balance, L2 state, and contract decodes with local verification.',
    extra: ['polygon', 'matic'],
  },
  'dsh-optimism': {
    niche: 'web3 & payments',
    headline: 'Optimism bridge for dsh agents',
    body: 'OP-stack reads - superchain context and L2 state in agent sessions.',
    extra: ['optimism', 'l2'],
  },
  'dsh-avalanche': {
    niche: 'web3 & payments',
    headline: 'Avalanche bridge for dsh agents',
    body: 'Subnet-aware reads - C-chain state and X and P chain context, decoded locally.',
    extra: ['avalanche', 'avax'],
  },
  'dsh-tron': {
    niche: 'web3 & payments',
    headline: 'Tron bridge for dsh agents',
    body: 'The USDT-lane chain - TRX reads, energy and bandwidth math, and TRC-20 decodes; the settlement rail of choice in Asia.',
    extra: ['tron', 'trx'],
  },
  'dsh-sui': {
    niche: 'web3 & payments',
    headline: 'Sui bridge for dsh agents',
    body: 'Move-based chain reads - objects, packages, and transaction intent decoded for review.',
    extra: ['sui', 'move'],
  },
  'dsh-aptos': {
    niche: 'web3 & payments',
    headline: 'Aptos bridge for dsh agents',
    body: 'Move-land reads - account resources and transaction history, decoded offline.',
    extra: ['aptos', 'move'],
  },
  'dsh-near': {
    niche: 'web3 & payments',
    headline: 'NEAR bridge for dsh agents',
    body: 'Sharded-chain reads - account state, access keys, and receipts in agent context.',
    extra: ['near'],
  },
  'dsh-ton': {
    niche: 'web3 & payments',
    headline: 'TON bridge for dsh agents',
    body: 'The Telegram chain - jetton reads and wallet activity, decoded with local rules.',
    extra: ['ton', 'telegram'],
  },
  'dsh-cardano': {
    niche: 'web3 & payments',
    headline: 'Cardano bridge for dsh agents',
    body: 'UTXO-with-eUTXO reads - addresses, staking, and Plutus script context.',
    extra: ['cardano', 'ada'],
  },
  'dsh-polkadot': {
    niche: 'web3 & payments',
    headline: 'Polkadot bridge for dsh agents',
    body: 'Parachain-aware reads - relay-chain state and XCM message context.',
    extra: ['polkadot', 'dot'],
  },
  'dsh-starknet': {
    niche: 'web3 & payments',
    headline: 'Starknet bridge for dsh agents',
    body: 'Cairo-land reads - contract state and events from an L2 built for proofs.',
    extra: ['starknet', 'cairo'],
  },
  'dsh-zksync': {
    niche: 'web3 & payments',
    headline: 'zkSync bridge for dsh agents',
    body: 'ZK-rollup reads - account state, proof context, and L1-L2 messaging.',
    extra: ['zksync', 'rollup'],
  },
  'dsh-bnb': {
    niche: 'web3 & payments',
    headline: 'BNB Chain bridge for dsh agents',
    body: 'The Binance-ecosystem chain lane - BSC reads and BEP-20 decodes with local verification; the chain seat while the exchange names sit with a third party.',
    extra: ['bnb', 'bsc'],
  },
  'dsh-dogecoin': {
    niche: 'web3 & payments',
    headline: 'Dogecoin bridge for dsh agents',
    body: 'DOGE UTXO reads and offline transaction verification, same trust rules as dsh-bitcoin.',
    extra: ['dogecoin', 'doge'],
  },
  'dsh-doge': {
    niche: 'web3 & payments',
    headline: 'The short form of the Dogecoin bridge',
    body: 'Compatibility name: the Dogecoin bridge ships as dsh-dogecoin; this form keeps the ticker spelling installable.',
    extra: ['doge', 'dogecoin'],
  },
  'dsh-xrp': {
    niche: 'web3 & payments',
    headline: 'XRP ledger bridge for dsh agents',
    body: 'Ledger reads - accounts, trust lines, and escrows decoded with local verification.',
    extra: ['xrp', 'ripple'],
  },
  'dsh-ripple': {
    niche: 'web3 & payments',
    headline: 'RippleNet-facing bridge for dsh agents',
    body: 'The company-form companion to dsh-xrp - XRPL reads plus the institutional product surface.',
    extra: ['ripple', 'xrp'],
  },
  'dsh-litecoin': {
    niche: 'web3 & payments',
    headline: 'Litecoin bridge for dsh agents',
    body: 'LTC UTXO reads - balances and history verified offline, script decodes included.',
    extra: ['litecoin', 'ltc'],
  },
  'dsh-monero': {
    niche: 'web3 & payments',
    headline: 'Monero-aware bridge for dsh agents',
    body: 'Privacy-respecting reads via your own view keys - the agent never sees spend keys, outputs stay yours.',
    extra: ['monero', 'privacy'],
  },
  'dsh-dai': {
    niche: 'web3 & payments',
    headline: 'DAI toolkit for dsh agents',
    body: 'The decentralized stablecoin lane - vault reads, stability-fee math, and on-chain supply checks.',
    extra: ['dai', 'maker'],
  },
  'dsh-circle': {
    niche: 'web3 & payments',
    headline: 'Circle bridge for dsh agents',
    body: 'The USDC issuer lane - mint and redemption reads, CCTP transfer context, and compliance surface.',
    extra: ['circle', 'usdc'],
  },
  'dsh-tether': {
    niche: 'web3 & payments',
    headline: 'Tether bridge for dsh agents',
    body: 'The USDT issuer lane - attestation reads and chain-issuance digests alongside dsh-usdt.',
    extra: ['tether', 'usdt'],
  },
  'dsh-uniswap': {
    niche: 'web3 & payments',
    headline: 'Uniswap bridge for dsh agents',
    body: 'Pool reads, quote math, and route drafts - swaps composed by the agent, approved and signed by you.',
    extra: ['uniswap', 'dex'],
  },
  'dsh-chainlink': {
    niche: 'web3 & payments',
    headline: 'Chainlink oracle bridge for dsh agents',
    body: 'Price feeds with proof context - every number the agent cites carries its oracle round.',
    extra: ['chainlink', 'oracle'],
  },
  'dsh-metamask': {
    niche: 'web3 & payments',
    headline: 'MetaMask-facing bridge for dsh agents',
    body: 'Snaps and connection flows exposed to harness sessions - signature requests surfaced through the approval seam, never auto-signed.',
    extra: ['metamask', 'wallet'],
  },
  'dsh-phantom': {
    niche: 'web3 & payments',
    headline: 'Phantom-facing bridge for dsh agents',
    body: 'The Solana-world wallet lane - connect, read balances, request signatures through approval; keys never touch the session.',
    extra: ['phantom', 'wallet'],
  },
  'dsh-trezor': {
    niche: 'web3 & payments',
    headline: 'Trezor-facing bridge for dsh agents',
    body: 'Hardware-held signing - the agent prepares transactions, the device confirms; the session never sees secrets.',
    extra: ['trezor', 'hardware-wallet'],
  },
  'dsh-alchemy': {
    niche: 'web3 & payments',
    headline: 'Alchemy bridge for dsh agents',
    body: 'The node-infra lane - enhanced APIs, webhooks, and NFT reads routed as agent tools with per-key budgets.',
    extra: ['alchemy', 'rpc'],
  },
  'dsh-infura': {
    niche: 'web3 & payments',
    headline: 'Infura bridge for dsh agents',
    body: 'The classic RPC lane - Ethereum and IPFS reads behind one key, budget-capped per session.',
    extra: ['infura', 'rpc'],
  },
  'dsh-etherscan': {
    niche: 'web3 & payments',
    headline: 'Etherscan bridge for dsh agents',
    body: 'Explorer reads with provenance - balances, transactions, and contract source with on-chain receipts attached.',
    extra: ['etherscan', 'explorer'],
  },
  'dsh-coingecko': {
    niche: 'web3 & payments',
    headline: 'CoinGecko bridge for dsh agents',
    body: 'Market data with citations - prices, volumes, and rankings every answer can link back to.',
    extra: ['coingecko', 'market-data'],
  },
  'dsh-defillama': {
    niche: 'web3 & payments',
    headline: 'DefiLlama bridge for dsh agents',
    body: 'TVL and protocol analytics - charts and chain breakdowns the agent cites by source.',
    extra: ['defillama', 'analytics'],
  },
  'dsh-dune': {
    niche: 'web3 & payments',
    headline: 'Dune bridge for dsh agents',
    body: 'SQL over the chain - dashboards queried live, results attached with query links for verification.',
    extra: ['dune', 'analytics'],
  },
  'dsh-hardhat': {
    niche: 'web3 & payments',
    headline: 'Hardhat bridge for dsh agents',
    body: 'Contract work in agent sessions - compile, test, and deploy flows over Hardhat with gas reports attached.',
    extra: ['hardhat', 'solidity'],
  },
  'dsh-foundry': {
    niche: 'web3 & payments',
    headline: 'Foundry bridge for dsh agents',
    body: 'The fast contract lane - forge build, test, and run as agent tools, fuzz results summarized.',
    extra: ['foundry', 'forge'],
  },
  'dsh-viem': {
    niche: 'web3 & payments',
    headline: 'Viem-facing bridge for dsh agents',
    body: 'TypeScript chain access as agent tools - the modern EVM client wired behind the approval seam.',
    extra: ['viem', 'evm'],
  },
  'dsh-wagmi': {
    niche: 'web3 & payments',
    headline: 'Wagmi-facing bridge for dsh agents',
    body: 'React hooks become agent calls - wallet connection state and contract reads surfaced to sessions.',
    extra: ['wagmi', 'evm'],
  },
  'dsh-cex': {
    niche: 'web3 & payments',
    headline: 'CEX toolkit for dsh agents',
    body: 'The generic exchange seat - one interface over exchange APIs (read balances, draft orders) while brand names sit elsewhere; keys stay in the OS keychain.',
    extra: ['cex', 'exchange'],
  },
  'dsh-adyen': {
    niche: 'web3 & payments',
    headline: 'Adyen bridge for dsh agents',
    body: 'Enterprise payment lane - payment reads, refund drafts, and settlement digests over the Adyen API.',
    extra: ['adyen', 'payments'],
  },
  'dsh-klarna': {
    niche: 'web3 & payments',
    headline: 'Klarna bridge for dsh agents',
    body: 'BNPL lane - order reads and payout digests over the Klarna merchant API.',
    extra: ['klarna', 'bnpl'],
  },
  'dsh-wise': {
    niche: 'web3 & payments',
    headline: 'Wise bridge for dsh agents',
    body: 'Cross-border lane - FX quotes, transfer drafts, and rate alerts over the Wise API; the go-global money mover.',
    extra: ['wise', 'fx'],
  },
  'dsh-payoneer': {
    niche: 'web3 & payments',
    headline: 'Payoneer bridge for dsh agents',
    body: 'The freelancer-payout lane - balance reads and withdrawal drafts, marketplaces reconciled.',
    extra: ['payoneer', 'payouts'],
  },
  'dsh-razorpay': {
    niche: 'web3 & payments',
    headline: 'Razorpay bridge for dsh agents',
    body: 'India-facing payments - order reads, settlement digests, and refund drafts over the Razorpay API.',
    extra: ['razorpay', 'payments'],
  },
  'dsh-square': {
    niche: 'web3 & payments',
    headline: 'Square bridge for dsh agents',
    body: 'POS and payments lane - sales digests, catalog reads, and refund drafts over the Square API.',
    extra: ['square', 'pos'],
  },
  'dsh-revolut': {
    niche: 'web3 & payments',
    headline: 'Revolut bridge for dsh agents',
    body: 'The neobank lane - account reads and transfer drafts over the business API, FX included.',
    extra: ['revolut', 'banking'],
  },
  'dsh-visa': {
    niche: 'web3 & payments',
    headline: 'Visa-facing bridge for dsh agents',
    body: 'The card-network lane - Developer Platform APIs surfaced with compliance guardrails; drafts only, no raw PANs in context.',
    extra: ['visa', 'cards'],
  },
  'dsh-mastercard': {
    niche: 'web3 & payments',
    headline: 'Mastercard-facing bridge for dsh agents',
    body: 'The other card network - developer APIs exposed with the same no-PAN discipline as dsh-visa.',
    extra: ['mastercard', 'cards'],
  },
  'dsh-solana': {
    niche: 'web3 & payments',
    headline: 'Solana bridge for dsh agents',
    body: 'SOL chain reads - balances, programs, and transaction history decoded with local verification where possible; the high-throughput lane beside dsh-eth. Registered externally; promoted into the curated core.',
    extra: ['solana', 'sol'],
  },
  'dsh-arbitrum': {
    niche: 'web3 & payments',
    headline: 'Arbitrum bridge for dsh agents',
    body: 'L2 reads and mainnet comparisons - balances, messages, and gas math in agent context. Registered externally; promoted into the curated core.',
    extra: ['arbitrum', 'l2'],
  },
  'dsh-usdt': {
    niche: 'web3 & payments',
    headline: 'USDT toolkit for dsh agents',
    body: 'The default settlement asset on TRON and Ethereum - issuance and redemption reads, chain-aware balances handled precisely. Registered externally; promoted into the curated core.',
    extra: ['usdt', 'tether', 'stablecoin'],
  },
  'dsh-stablecoin': {
    niche: 'web3 & payments',
    headline: 'Stablecoin rail toolkit for dsh agents',
    body: 'One surface over USDC, USDT, and DAI - issuance, redemption, and chain-aware balance math with settlement guarantees stated. Registered externally; promoted into the curated core.',
    extra: ['stablecoin', 'settlement'],
  },
  'dsh-ledger': {
    niche: 'web3 & payments',
    headline: 'Ledger-facing bridge for dsh agents',
    body: 'Hardware signing lane - transaction drafts routed to the device, results read back and decoded. Registered externally; promoted into the curated core.',
    extra: ['ledger', 'hardware-wallet'],
  },
  'dsh-lightning': {
    niche: 'web3 & payments',
    headline: 'Lightning Network toolkit for dsh agents',
    body: 'Fast settlement lane - invoice reads, channel state, and payment drafts over LND and CLN with local verification. Registered externally; promoted into the curated core.',
    extra: ['lightning', 'payments'],
  },
  'dsh-solidity': {
    niche: 'web3 & payments',
    headline: 'Solidity toolkit for dsh agents',
    body: 'The contract language as a first-class surface - static checks, ABI decoding, and upgrade-safety reviews in session. Registered externally; promoted into the curated core.',
    extra: ['solidity', 'evm'],
  },
  'dsh-pay': {
    niche: 'web3 & payments',
    headline: 'The generic payment seat for dsh agents',
    body: 'One interface over every lane - cards (dsh-stripe, dsh-paypal), crypto (dsh-usdc, dsh-x402), and banks (dsh-wise) - behind a single spend-policy gate. Registered externally; promoted into the curated core.',
    extra: ['pay', 'payments'],
  },
  'dsh-dex': {
    niche: 'web3 & payments',
    headline: 'DEX toolkit for dsh agents',
    body: 'On-chain swaps with quotes and routes - pool reads, slippage math, and swap drafts; the decentralized answer to the third-party-held exchange bridges. Registered externally; promoted into the curated core.',
    extra: ['dex', 'swaps'],
  },
  'dsh-hyperliquid': {
    niche: 'web3 & payments',
    headline: 'Hyperliquid bridge for dsh agents',
    body: 'The perp DEX lane - positions, funding, and order drafts over the Hyperliquid API; on-chain by default. Registered externally; promoted into the curated core.',
    extra: ['hyperliquid', 'perps'],
  },
// ---- channels -------------------------------------------------------
  'dsh-tiktok': {
    niche: 'channels',
    headline: 'TikTok channel bridge for dsh bots',
    body: 'Publish run outputs as TikTok drafts - scripts, captions, and hashtags composed from runs.jsonl, approved before posting; the short-video outbound lane.',
    extra: ['tiktok', 'channel'],
  },
  'dsh-instagram': {
    niche: 'channels',
    headline: 'Instagram channel bridge for dsh bots',
    body: 'Post carousels and digests to Instagram - content drafted from run summaries, alt text included, human-approved before publish.',
    extra: ['instagram', 'channel'],
  },
  'dsh-facebook': {
    niche: 'channels',
    headline: 'Facebook channel bridge for dsh bots',
    body: 'Pages and groups as bot outlets - scheduled posts, comment triage, and Messenger handoff via the page webhook.',
    extra: ['facebook', 'channel'],
  },
  'dsh-youtube': {
    niche: 'channels',
    headline: 'YouTube channel bridge for dsh bots',
    body: 'Turn session replays into YouTube drafts - title, description, chapters, and thumbnail drafted by the agent, uploaded after approval.',
    extra: ['youtube', 'channel'],
  },
  'dsh-reddit': {
    niche: 'channels',
    headline: 'Reddit channel bridge for dsh bots',
    body: 'Read subreddits, answer as the bot, and crosspost digests - rate-limit aware, subreddit rules respected, every post human-approved.',
    extra: ['reddit', 'channel'],
  },
  'dsh-linkedin': {
    niche: 'channels',
    headline: 'LinkedIn channel bridge for dsh bots',
    body: 'Professional-network presence on autopilot drafts - posts and articles composed from run summaries, B2B tone enforced, scheduled after review.',
    extra: ['linkedin', 'channel'],
  },
  'dsh-threads': {
    niche: 'channels',
    headline: 'Threads channel bridge for dsh bots',
    body: 'Short-form posts to Threads - digest threads composed from runs.jsonl, cross-posted with dsh-instagram in one approval.',
    extra: ['threads', 'channel'],
  },
  'dsh-pinterest': {
    niche: 'channels',
    headline: 'Pinterest channel bridge for dsh bots',
    body: 'Pins and boards as a visual archive - run outputs pinned with generated covers, boards per project and per week.',
    extra: ['pinterest', 'channel'],
  },
  'dsh-snapchat': {
    niche: 'channels',
    headline: 'Snapchat channel bridge for dsh bots',
    body: 'Spotlight digests and streak updates - short visual summaries composed from run summaries, sent after approval.',
    extra: ['snapchat', 'channel'],
  },
  'dsh-twitch': {
    niche: 'channels',
    headline: 'Twitch bridge for dsh agents',
    body: 'Chat moderation and stream assistance - the agent watches chat, answers routine questions, and flags escalation while you stream.',
    extra: ['twitch', 'channel'],
  },
  'dsh-medium': {
    niche: 'channels',
    headline: 'Medium channel bridge for dsh bots',
    body: 'Long-form drafts from session deep-dives - the agent structures the essay, you edit and publish; versioned drafts per post.',
    extra: ['medium', 'channel'],
  },
  'dsh-substack': {
    niche: 'channels',
    headline: 'Substack channel bridge for dsh bots',
    body: 'Newsletters from run digests - drafts composed weekly from runs.jsonl, subject lines A/B ready, sent after human review.',
    extra: ['substack', 'newsletter'],
  },
  'dsh-bluesky': {
    niche: 'channels',
    headline: 'Bluesky channel bridge for dsh bots',
    body: 'AT Protocol posts from the bot - digests and replies, handle-based identity, every post human-approved before it ships.',
    extra: ['bluesky', 'atproto'],
  },
  'dsh-mastodon': {
    niche: 'channels',
    headline: 'Mastodon channel bridge for dsh bots',
    body: 'Fediverse presence for bots - instance-aware posting, content warnings set, replies triaged per instance rules.',
    extra: ['mastodon', 'fediverse'],
  },
  'dsh-messenger': {
    niche: 'channels',
    headline: 'Messenger channel bridge for dsh bots',
    body: 'The Meta page inbox as a bot surface - customer FAQs answered by the agent, handoff to humans on low confidence.',
    extra: ['messenger', 'channel'],
  },
  'dsh-kakao': {
    niche: 'channels',
    headline: 'KakaoTalk channel bridge for dsh bots',
    body: 'Korea-facing bot lane - KakaoTalk channel messages in and out, templates for alerts, digests delivered where Korean users live.',
    extra: ['kakao', 'channel'],
  },
  'dsh-mailchimp': {
    niche: 'channels',
    headline: 'Mailchimp bridge for dsh bots',
    body: 'Campaign drafts from run digests - segments chosen by the agent, subject lines ranked, nothing sends without approval.',
    extra: ['mailchimp', 'email'],
  },
  'dsh-newsletter': {
    niche: 'channels',
    headline: 'Newsletter toolkit for dsh bots',
    body: 'The format itself as a channel - issue templates, digests from runs.jsonl, subscribe and unsubscribe handling, deliverability checks before send.',
    extra: ['newsletter', 'email'],
  },
  'dsh-whatsapp': {
    niche: 'channels',
    headline: 'WhatsApp channel bridge for dsh bots',
    body: 'The world-default messaging lane - bot digests and customer conversations over the Cloud API, template messages for alerts, human handoff on low confidence. Registered externally; promoted into the curated core.',
    extra: ['whatsapp', 'channel'],
  },
  'dsh-line': {
    niche: 'channels',
    headline: 'LINE channel bridge for dsh bots',
    body: 'The Japan-and-Southeast-Asia lane - LINE official-account messages in and out, rich menus as command surfaces, digests delivered where LINE users live. Registered externally; promoted into the curated core.',
    extra: ['line', 'channel'],
  },
  'dsh-twitter': {
    niche: 'channels',
    headline: 'X (Twitter) channel bridge for dsh bots',
    body: 'Post run summaries and digests to X - threads composed from runs.jsonl, drafts approved before sending; the outbound lane for bot output. Registered externally; promoted into the curated core.',
    extra: ['twitter', 'x', 'channel'],
  },
  'dsh-amazon': {
    niche: 'channels',
    headline: 'Amazon bridge for dsh agents',
    body: 'Listing research and ops - SP-API reads for pricing and reviews, listing drafts and A+ content proposed by the agent, approved before submission.',
    extra: ['amazon', 'ecommerce'],
  },
  'dsh-shopify': {
    niche: 'channels',
    headline: 'Shopify bridge for dsh agents',
    body: 'Store ops as agent work - product drafts, inventory reads, and order triage over the Admin API, every mutation through the approval seam.',
    extra: ['shopify', 'ecommerce'],
  },
  'dsh-ebay': {
    niche: 'channels',
    headline: 'eBay bridge for dsh agents',
    body: 'Listing and resale research - price comps from live listings, draft titles and specifics proposed, revisions approved before they go live.',
    extra: ['ebay', 'ecommerce'],
  },
  'dsh-etsy': {
    niche: 'channels',
    headline: 'Etsy bridge for dsh agents',
    body: 'Handmade-market ops - listing drafts, tag research, and shop stats digests, composed by the agent for seller review.',
    extra: ['etsy', 'ecommerce'],
  },
  'dsh-stripe': {
    niche: 'channels',
    headline: 'Stripe bridge for dsh agents',
    body: 'Payments as agent surface - invoices drafted, subscriptions inspected, revenue digests weekly; every write goes through the approval seam.',
    extra: ['stripe', 'payments'],
  },
  'dsh-paypal': {
    niche: 'channels',
    headline: 'PayPal bridge for dsh agents',
    body: 'The consumer-payment lane - transaction reads, refund drafts with reason codes, and monthly statements summarized by the agent.',
    extra: ['paypal', 'payments'],
  },
  'dsh-shopee': {
    niche: 'channels',
    headline: 'Shopee bridge for dsh agents',
    body: 'Southeast-Asia storefront ops - listing reads, price-change drafts, and campaign calendars, agent-composed for seller approval.',
    extra: ['shopee', 'ecommerce'],
  },
  'dsh-intercom': {
    niche: 'channels',
    headline: 'Intercom bridge for dsh agents',
    body: 'Support inbox as bot lane - conversations triaged, routine replies drafted in your voice, handoff notes for humans on hard tickets.',
    extra: ['intercom', 'support'],
  },
  'dsh-hubspot': {
    niche: 'channels',
    headline: 'HubSpot bridge for dsh agents',
    body: 'The CRM as agent surface - contact research, deal-stage digests, and drafted follow-ups, every write approved before it lands.',
    extra: ['hubspot', 'crm'],
  },
  'dsh-zendesk': {
    niche: 'channels',
    headline: 'Zendesk bridge for dsh agents',
    body: 'Ticket queue as bot lane - macros suggested, routine tickets resolved by draft, escalation with full context attached.',
    extra: ['zendesk', 'support'],
  },
  'dsh-salesforce': {
    niche: 'channels',
    headline: 'Salesforce bridge for dsh agents',
    body: 'Enterprise CRM ops - SOQL reads for account research, opportunity digests, and drafted touchpoints; writes gated by policy.',
    extra: ['salesforce', 'crm'],
  },
  'dsh-ensemble': {
    niche: 'multi-agent',
    headline: 'Model ensembles for dsh',
    body: 'N models answer in parallel, answers merged - cross-vendor consensus for high-stakes calls; disagreement is signal, not noise.',
    extra: ['ensemble', 'consensus'],
  },
  'dsh-broker': {
    niche: 'multi-agent',
    headline: 'Task broker for agent fleets',
    body: 'A matchmaking layer between queued work and idle bots - capability tags, load, and affinity in one routing decision.',
    extra: ['broker', 'routing'],
  },
  'dsh-swarm': {
    niche: 'multi-agent',
    headline: 'Multi-agent swarm orchestration for dsh',
    body: 'One declarative swarm - auditable routing, hard budget caps, and a shared run ledger; members run as dsh-bot manifests. Registered externally; promoted into the curated core as the flagship multi-agent name.',
    extra: ['swarm', 'multi-agent', 'orchestration'],
  },
  'dsh-delegate': {
    niche: 'multi-agent',
    headline: 'Delegation tool for dsh agents',
    body: 'A model-facing tool that lets one agent spawn, supervise, and collect from sub-agents - spawn depth and token budgets capped by policy; the primitive under crews and swarms.',
    extra: ['delegate', 'subagent', 'spawn'],
  },
  'dsh-queue': {
    niche: 'multi-agent',
    headline: 'Durable task queues for dsh bots',
    body: 'Named queues with priorities, visibility timeouts, and dead-letter handling - the persistent backbone dsh-jobs dispatches over; local files first, no broker required.',
    extra: ['queue', 'jobs', 'tasks'],
  },
  'dsh-council': {
    niche: 'multi-agent',
    headline: 'Council-of-agents deliberation for dsh',
    body: 'N agents answer independently, critique, and converge - debate as a harness surface for high-stakes calls; verdicts ship with recorded dissent.',
    extra: ['council', 'debate', 'consensus'],
  },
  // ---- role presets ------------------------------------------------------
  // The persona form of the multi-agent story: one install = one role seat
  // for a session, a crew, or a swarm. Third-party dsh-crew ships fixed
  // roles; these names keep every role composable and ours.
  'dsh-frontend': {
    niche: 'role presets',
    headline: 'Frontend developer role preset',
    body: 'A frontend specialist persona - component architecture instincts, accessibility and bundle-size reflexes, edit proposals biased toward the rendering layer. Composes into crews and swarms as the frontend seat.',
    extra: ['frontend', 'react', 'vue', 'persona'],
  },
  'dsh-backend': {
    niche: 'role presets',
    headline: 'Backend developer role preset',
    body: 'A backend specialist persona - API and schema design, failure modes, caching and concurrency instincts; the counterpart to dsh-frontend and the default engineer seat in any crew.',
    extra: ['backend', 'api', 'server', 'persona'],
  },
  'dsh-fullstack': {
    niche: 'role presets',
    headline: 'Full-stack developer role preset',
    body: 'The generalist persona that inherits both ends - biased toward shipping vertical slices end to end, with the judgment to know when to split work into specialists.',
    extra: ['fullstack', 'persona'],
  },
  'dsh-dev': {
    niche: 'role presets',
    headline: 'Developer role preset (short form)',
    body: 'Compatibility name: the generic developer persona; the specialist forms ship as dsh-frontend and dsh-backend.',
    extra: ['dev', 'developer', 'persona'],
  },
  'dsh-engineer': {
    niche: 'role presets',
    headline: 'Software engineer role preset',
    body: 'The discipline-first engineer persona - tests before refactors, small diffs, reversible changes; the seat every other preset composes with.',
    extra: ['engineer', 'persona'],
  },
  'dsh-devops': {
    niche: 'role presets',
    headline: 'DevOps role preset',
    body: 'Pipelines, containers, and environments as first-class citizens - a persona that reads CI logs like prose and treats infrastructure as code. Registered externally; promoted into the curated core.',
    extra: ['devops', 'ci', 'infra', 'persona'],
  },
  'dsh-sre': {
    niche: 'role presets',
    headline: 'Site reliability engineer role preset',
    body: 'The SRE persona - SLIs and SLOs, incident forensics, blameless postmortems; biased toward observability and rollback paths over feature work. Registered externally; promoted into the curated core.',
    extra: ['sre', 'reliability', 'incident', 'persona'],
  },
  'dsh-dba': {
    niche: 'role presets',
    headline: 'Database administrator role preset',
    body: 'Schema reviews, index strategy, and query plans - the DBA persona for crews touching data layers; the role behind the dsh-db tool surface.',
    extra: ['dba', 'database', 'persona'],
  },
  'dsh-architect': {
    niche: 'role presets',
    headline: 'Software architect role preset',
    body: 'System-level judgment - boundaries, seams, and tradeoff memos before code; the architect seat crews consult before the first commit.',
    extra: ['architect', 'design', 'persona'],
  },
  'dsh-designer': {
    niche: 'role presets',
    headline: 'Product designer role preset',
    body: 'Interface judgment as a persona - hierarchy, typography, and flow critiques on the diffs a crew produces; pairs with dsh-ux.',
    extra: ['designer', 'ui', 'persona'],
  },
  'dsh-tester': {
    niche: 'role presets',
    headline: 'QA tester role preset',
    body: 'The quality persona - test matrices, edge cases, and regression instincts applied to every proposal; the adversarial reader every crew needs. (The qa-spelled name ships as a community package.)',
    extra: ['tester', 'qa', 'quality', 'persona'],
  },
  'dsh-analyst': {
    niche: 'role presets',
    headline: 'Data analyst role preset',
    body: 'Questions before dashboards - the analyst persona that frames metrics, guards against survivorship bias, and writes SQL you can audit.',
    extra: ['analyst', 'data', 'persona'],
  },
  'dsh-algorithm': {
    niche: 'role presets',
    headline: 'Algorithm engineer role preset',
    body: 'The algorithms persona - complexity instincts, evaluation methodology, and the honesty to prefer boring solutions; complements dsh-ml.',
    extra: ['algorithm', 'persona'],
  },
  'dsh-ios': {
    niche: 'role presets',
    headline: 'iOS developer role preset',
    body: 'The Apple-platform specialist - Swift conventions, interface-guideline reflexes, and App Store release hygiene.',
    extra: ['ios', 'swift', 'persona'],
  },
  'dsh-android': {
    niche: 'role presets',
    headline: 'Android developer role preset',
    body: 'The Android specialist - Kotlin idioms, fragmentation strategy, and Play release hygiene.',
    extra: ['android', 'kotlin', 'persona'],
  },
  'dsh-embedded': {
    niche: 'role presets',
    headline: 'Embedded developer role preset',
    body: 'Firmware and hardware-adjacent judgment - resource ceilings, timing, and safety margins; the persona for crews that ship to devices.',
    extra: ['embedded', 'firmware', 'persona'],
  },
  'dsh-security': {
    niche: 'role presets',
    headline: 'Security engineer role preset',
    body: 'The adversarial persona - threat modeling, dependency audits, and secrets hygiene; pairs with dsh-secrets and dsh-policy.',
    extra: ['security', 'appsec', 'persona'],
  },
  'dsh-researcher': {
    niche: 'role presets',
    headline: 'Researcher role preset',
    body: "The crew's evidence gatherer - sourced claims, primary documents, and the discipline to say what is not known; the role third-party crew packages made popular, as a standalone preset.",
    extra: ['research', 'persona'],
  },
  'dsh-product-manager': {
    niche: 'role presets',
    headline: 'Product manager role preset',
    body: 'The PM persona - scope carving, acceptance criteria, and status prose that executives actually read; the default non-engineering seat in a crew. (The pm-spelled name ships as a community package.)',
    extra: ['product-manager', 'pm', 'persona'],
  },
  'dsh-hiring-manager': {
    niche: 'role presets',
    headline: 'Hiring manager role preset',
    body: 'The hiring-manager persona - bar calibration, interview debriefs, and evidence-based scorecards over the dsh-hiring pipeline.',
    extra: ['hiring-manager', 'interview', 'persona'],
  },
  'dsh-engineering-manager': {
    niche: 'role presets',
    headline: 'Engineering manager role preset',
    body: 'The EM persona - growth feedback, delegation plans, and delivery-risk reads; the management counterpart to dsh-architect.',
    extra: ['engineering-manager', 'persona'],
  },
  'dsh-agent': {
    niche: 'agent capabilities',
    headline: 'Agent pattern library for dsh',
    body: 'Ready-made agent patterns - researcher, reviewer, runner - as preset rows you can fork; the singular companion to the agent registry (dsh-agents).',
    extra: ['agent', 'patterns'],
  },
  'dsh-workflows': {
    niche: 'agent capabilities',
    headline: 'The plural form of Workflow Studio',
    body: 'Compatibility name: Workflow Studio ships as dsh-workflow; this form keeps the plural spelling installable.',
    extra: ['workflow', 'workflows'],
  },
  'dsh-channels': {
    niche: 'channels',
    headline: 'Chat-channel framework for dsh bots',
    body: 'The shared substrate the community platform bridges plug into - telegram, discord, slack, and feishu adapters all speak one channel contract, with approvals gated per platform.',
    extra: ['channels', 'chat', 'bridge'],
  },
  'dsh-tasks': {
    niche: 'agent capabilities',
    headline: 'Durable task tracking for dsh sessions',
    body: 'Checklist state that survives compaction and session switches, linked from planner trees and surfaced in the GUI.',
    extra: ['tasks', 'todo', 'checklist'],
  },
  // ---- interaction -------------------------------------------------------
  'dsh-listen': {
    niche: 'interaction',
    headline: 'Always-listening input loop',
    body: 'The hands-free mode - voice activity detected, hot phrases routed to the active session, everything else stays local.',
    extra: ['listen', 'voice'],
  },
  'dsh-cast': {
    niche: 'interaction',
    headline: 'Cast sessions to nearby screens',
    body: 'One-click presentation of a live session to a TV, projector, or second browser - read-only, zero-setup casting over the LAN.',
    extra: ['cast', 'screen'],
  },
  // The attention/voice/input layer - patterns the best agents proved:
  // interruptible voice (ChatGPT), mid-run steering (Claude Code),
  // @-mentions (Cursor), ambient presence (Devin). The interaction layer
  // is the second-most-colonized niche after multi-agent; nine names
  // (speak, notify, status, hud, theme, feedback, replay, pulse, history)
  // already ship as third-party community packages.
  'dsh-tts': {
    niche: 'interaction',
    headline: 'Spoken status and voice alerts for dsh sessions',
    body: 'The voice-alert layer - results summaries, approval-ready prompts, and bot outcomes spoken aloud (macOS say / Windows SAPI / Piper); pluggable voices, off by default.',
    extra: ['tts', 'speech', 'voice', 'alerts'],
  },
  'dsh-stt': {
    niche: 'interaction',
    headline: 'Speech-to-text input for dsh sessions',
    body: "Dictate prompts to any session - push-to-talk and hands-free modes, locally processed by default (whisper.cpp); typed input's faster sibling.",
    extra: ['stt', 'dictation', 'whisper', 'voice'],
  },
  'dsh-speech': {
    niche: 'interaction',
    headline: 'Bidirectional voice mode with barge-in',
    body: 'The agent speaks and listens with interruptible back-and-forth - speak to redirect mid-answer; the ChatGPT-voice pattern for a harness, composed from dsh-tts and dsh-stt.',
    extra: ['voice', 'speech', 'conversation'],
  },
  'dsh-wake': {
    niche: 'interaction',
    headline: 'Wake-word activation for the voice loop',
    body: "A local 'hey dsh' spotter that opens the voice loop from anywhere - no cloud round-trip, no always-on recording that leaves the machine.",
    extra: ['wake-word', 'voice', 'hands-free'],
  },
  'dsh-audio': {
    niche: 'interaction',
    headline: 'Audio I/O substrate for the harness',
    body: 'The shared layer dsh-tts and dsh-stt build on - device selection, voice-activity detection, and output routing in one service. Registered externally; promoted into the curated core.',
    extra: ['audio', 'io'],
  },
  'dsh-toast': {
    niche: 'interaction',
    headline: 'Toast notifications for the dsh web GUI',
    body: 'Transient, stackable, clickable in-app notices - run finished, approval ready, budget hit. (The notify-spelled desktop bridge ships as a community package.)',
    extra: ['toast', 'notification'],
  },
  'dsh-bell': {
    niche: 'interaction',
    headline: 'Terminal bell and title management',
    body: 'The minimal attention primitive - bell on approval-ready and completion, plus live terminal-title state (model, elapsed, waiting-on) for every session tab.',
    extra: ['bell', 'terminal'],
  },
  'dsh-dnd': {
    niche: 'interaction',
    headline: 'Focus-aware notification routing',
    body: 'Do-not-disturb that actually routes - silence during focus sessions, batch digests after, escalate only what matters; the policy layer over dsh-alert and dsh-toast.',
    extra: ['dnd', 'focus', 'mute'],
  },
  'dsh-nudge': {
    niche: 'interaction',
    headline: 'Proactive agent check-ins',
    body: 'The agent nudges you when it needs a decision, when a run has waited too long, or when work finished while you were away - a cadence you configure, not a firehose.',
    extra: ['nudge', 'reminder'],
  },
  'dsh-presence': {
    niche: 'interaction',
    headline: 'Teammate presence for agents',
    body: 'Working / thinking / waiting-on-you states exposed like a chat contact list, so parallel sessions read at a glance. (The status-spelled line ships as a community package.)',
    extra: ['presence', 'status'],
  },
  'dsh-progress': {
    niche: 'interaction',
    headline: 'Progress affordances for long work',
    body: 'Plan trees rendered as trackable progress with ETAs - in the GUI as bars, in the terminal as one-line summaries that stay honest.',
    extra: ['progress', 'eta'],
  },
  'dsh-ambient': {
    niche: 'interaction',
    headline: 'Ambient status display',
    body: 'A desk-clock mode for a spare screen or tablet - live session presence, budgets, and the current action, glanceable from across the room.',
    extra: ['ambient', 'dashboard'],
  },
  'dsh-next': {
    niche: 'interaction',
    headline: 'Next-step suggestions after each answer',
    body: 'Continue, commit, test, or delegate - one-click follow-ups that keep momentum; the Copilot-pattern affordance. Registered externally; promoted into the curated core.',
    extra: ['next', 'suggestions'],
  },
  'dsh-attach': {
    niche: 'interaction',
    headline: 'Attachments for prompts',
    body: 'Drag-and-drop files, screenshots, and images into any session; paste-as-file; everything lands in the workspace, not in chat limbo.',
    extra: ['attach', 'upload', 'paste'],
  },
  'dsh-mention': {
    niche: 'interaction',
    headline: '@-mentions in prompts',
    body: '@file, @dir, @agent, and @bot references resolved at prompt time into exact context - the reference grammar Cursor made essential.',
    extra: ['mention', 'reference'],
  },
  'dsh-steer': {
    niche: 'interaction',
    headline: 'Mid-run steering',
    body: 'Queue messages and redirects while the agent works - they land at the next checkpoint instead of being lost or interrupting; the Claude Code pattern.',
    extra: ['steer', 'queue'],
  },
  'dsh-autocomplete': {
    niche: 'interaction',
    headline: 'Prompt autocomplete',
    body: 'History- and workspace-aware completion for the prompt box; distinct from shell completions (dsh-completions).',
    extra: ['autocomplete'],
  },
  'dsh-tour': {
    niche: 'interaction',
    headline: 'Interactive product tours',
    body: 'First-run walkthroughs for panels and features, step-annotated in the live GUI - the onboarding layer mature products ship. (Community theme packs ship separately.)',
    extra: ['tour', 'onboarding'],
  },
  'dsh-mirror': {
    niche: 'interaction',
    headline: 'Mirror a session to a second surface',
    body: 'A read-only live view for another screen, browser, or projector - present what the agent is doing without leaning over shoulders.',
    extra: ['mirror', 'screen'],
  },
  // ---- ui ----------------------------------------------------------------
  'dsh-panel': {
    niche: 'ui',
    headline: 'Custom panel framework for the dsh web GUI',
    body: 'Compose your own side panels from widgets - layout saved per profile, panels hot-swappable.',
    extra: [],
  },
  'dsh-widget': {
    niche: 'ui',
    headline: 'Widget library for the dsh web GUI',
    body: 'Clocks, token meters, status tiles - small composable widgets for custom panels and the home view.',
    extra: [],
  },
  'dsh-zen': {
    niche: 'ui',
    headline: 'Zen mode for the dsh web GUI',
    body: 'Distraction-free single-column typography - hide chrome, widen the conversation, keep the keyboard.',
    extra: [],
  },
  'dsh-sound': {
    niche: 'ui',
    headline: 'Sound design for the DeepSeek Harness',
    body: 'Subtle completion and approval-ready chimes - off by default, tasteful when on.',
    extra: [],
  },
  'dsh-files': {
    niche: 'ui',
    headline: 'File manager panel for the dsh web GUI',
    body: "Browse and edit workspace files in the GUI, with every write passing the harness approval seam. The Finder's sibling: browsing when you know where things are.",
    extra: [],
  },
  'dsh-diff': {
    niche: 'ui',
    headline: 'Turn diff viewer for the dsh web GUI',
    body: 'Review every file edit a turn made, side by side, before or after approval - one glance instead of scrolling tool output.',
    extra: ['diff'],
  },
  // ---- data --------------------------------------------------------------
  'dsh-vector': {
    niche: 'data',
    headline: 'Vector store bridge for dsh agents',
    body: 'Embeddings in, nearest neighbors out - one tool surface over local (sqlite-vec) and remote stores, with per-collection budgets.',
    extra: ['vector', 'embeddings'],
  },
  'dsh-embed': {
    niche: 'data',
    headline: 'Embedding pipeline for dsh agents',
    body: 'Chunk, embed, and index workspace files - the ingestion side of retrieval, incremental by mtime, budget-capped per run.',
    extra: ['embeddings', 'ingestion'],
  },
  'dsh-retrieval': {
    niche: 'data',
    headline: 'Retrieval surface for dsh agents',
    body: 'A single retrieve() with reranking and citations - the read side of the RAG loop, wired into the prompt seam so context arrives sourced.',
    extra: ['retrieval', 'rag'],
  },
  'dsh-index': {
    niche: 'data',
    headline: 'Workspace index for dsh agents',
    body: 'A live symbol-and-file index of the workspace - who defines what, updated on save; the lookup layer under retrieval.',
    extra: ['index', 'symbols'],
  },
  'dsh-export': {
    niche: 'data',
    headline: 'Export sessions from the DeepSeek Harness',
    body: 'Markdown, PDF, JSON - images and tool output inlined, one session or the whole home.',
    extra: ['export'],
  },
  'dsh-archive': {
    niche: 'data',
    headline: 'Archive cold sessions to compressed bundles',
    body: 'Move old sessions out of the live store, keep them searchable without unpacking, restore on demand.',
    extra: [],
  },
  'dsh-cloud': {
    niche: 'data',
    headline: 'Cloud sync for dsh homes',
    body: 'Encrypted session and settings sync to your own storage backend - no vendor lock, endpoints you choose.',
    extra: ['sync'],
  },
  'dsh-link': {
    niche: 'data',
    headline: 'Share links for dsh sessions',
    body: 'Publish a read-only snapshot of a conversation - one command, one URL, no account.',
    extra: ['sharing'],
  },
  // ---- ops ---------------------------------------------------------------
  'dsh-sandbox': {
    niche: 'ops',
    headline: 'Sandboxed execution for agent commands',
    body: 'Commands that must not touch the host run inside a seatbelt sandbox - filesystem and network policy enforced per invocation.',
    extra: ['sandbox', 'seatbelt'],
  },
  'dsh-isolate': {
    niche: 'ops',
    headline: 'Isolation realms for dsh sessions',
    body: 'Cordis isolate realms exposed as a user feature - a session and its plugins run in a private realm, side effects bounded by contract.',
    extra: ['isolate', 'realm'],
  },
  'dsh-fork': {
    niche: 'ops',
    headline: 'Session forking',
    body: 'Fork a live session - full conversation state copied, both branches continue independently; the try-both-ways primitive.',
    extra: ['fork', 'branch'],
  },
  'dsh-headless': {
    niche: 'ops',
    headline: 'Headless mode toolkit',
    body: 'The no-GUI invocation contract - profile setup, prompt capture, and exit-code discipline for headless dsh runs; the layer dsh-bot spawns through.',
    extra: ['headless', 'cli', 'automation'],
  },
  'dsh-daemon': {
    niche: 'ops',
    headline: 'Background daemon for dsh bots',
    body: 'A launchd/systemd-friendly supervisor that keeps scheduled bots alive - starts on boot, restarts on crash, fronts the dsh-bot health socket.',
    extra: ['daemon', 'service', 'supervisor'],
  },
  'dsh-run': {
    niche: 'ops',
    headline: 'Programmatic one-shot runner',
    body: 'Run a dsh session from code or CI - argv in, structured result out; the thin sibling of dsh-bot for non-scheduled work.',
    extra: ['run', 'runner', 'ci'],
  },
  'dsh-sessions': {
    niche: 'ops',
    headline: 'Session manager and browser',
    body: 'List, inspect, and resume past dsh sessions from terminal or GUI - filters by project, date, and outcome; the multi-session ops view.',
    extra: ['sessions', 'resume', 'history'],
  },
  'dsh-logs': {
    niche: 'ops',
    headline: 'Structured log viewer for the dsh host',
    body: 'Filter by session, tool, or level; jump from a log line to the conversation node that produced it.',
    extra: ['logs'],
  },
  'dsh-metrics': {
    niche: 'ops',
    headline: 'Token and latency metrics for the DeepSeek Harness',
    body: 'Per session, model, and provider - with daily budgets and a spend projection.',
    extra: ['metrics', 'tokens'],
  },
  'dsh-alert': {
    niche: 'ops',
    headline: 'Alerts for dsh sessions',
    body: 'Webhooks, sound, or system notification when a session needs input or fails - walk away safely.',
    extra: ['alerts', 'notifications'],
  },
  'dsh-health': {
    niche: 'ops',
    headline: 'Live health status for dsh installs',
    body: "Liveness of the web host, model adapters, and credentials at a glance - the always-on display to dsh-selfrepair's repair.",
    extra: ['health'],
  },
  'dsh-clean': {
    niche: 'ops',
    headline: 'Safe-clean the dsh home',
    body: 'Caches, spill files, stale backups - a preview of exactly what goes, then it goes.',
    extra: [],
  },
  'dsh-reset': {
    niche: 'ops',
    headline: 'Reset dsh profiles to a known state',
    body: 'Snapshot before experimenting, restore after - the whole profile, not just settings.',
    extra: [],
  },
  'dsh-serve': {
    niche: 'ops',
    headline: 'Serve-mode extras for the dsh web GUI',
    body: 'Auth, TLS, and shareable URLs for the web GUI on a LAN - one flag, safe defaults.',
    extra: [],
  },
  'dsh-jobs': {
    niche: 'ops',
    headline: 'Background jobs for dsh bots',
    body: 'The execution half of the bot framework - queued and recurring runs with logs, retries, and a dead-letter view.',
    extra: ['jobs', 'queue', 'cron'],
  },
  // ---- security ----------------------------------------------------------
  'dsh-secrets': {
    niche: 'security',
    headline: 'Secrets handling for dsh agents',
    body: 'Reference credentials by name, never paste values into prompts - agent sees the reference, never the key.',
    extra: ['secrets'],
  },
  'dsh-policy': {
    niche: 'security',
    headline: 'Approval policy engine for the DeepSeek Harness',
    body: 'Per-tool, per-path rules that decide which agent actions need a human - versioned with the repo, not clicked in a dialog.',
    extra: ['policy', 'approval'],
  },
  'dsh-permission': {
    niche: 'security',
    headline: 'Permission scopes for dsh tools',
    body: 'Grant a session read-only, write-scope, or network access explicitly - scopes shown live in the header.',
    extra: ['permissions'],
  },
  // ---- work & hiring -----------------------------------------------------
  'dsh-hiring': {
    niche: 'work & hiring',
    headline: 'Hiring workflow for engineering teams',
    body: 'From JD to offer - screening rubrics, interview kits, and scorecards the agent drafts and the human approves; every candidate decision traceable to evidence. Pairs with dsh-recruit and dsh-hr.',
    extra: ['hiring', 'recruiting', 'ats'],
  },
  'dsh-job': {
    niche: 'work & hiring',
    headline: 'The singular form of the background-jobs runner',
    body: 'Compatibility name: background jobs ship as dsh-jobs; this form keeps the singular spelling installable.',
    extra: ['job', 'jobs'],
  },
  'dsh-talent': {
    niche: 'work & hiring',
    headline: 'Talent pool manager',
    body: 'A local, private candidate database - search by skill graph, track outreach and status, export anytime; an ATS you own, no SaaS lock-in.',
    extra: ['talent', 'ats', 'candidates'],
  },
  'dsh-jd': {
    niche: 'work & hiring',
    headline: 'Job description library',
    body: 'Versioned JD templates with skill and level ladders - draft, diff, and reuse across openings; the recruiter counterpart to dsh-snippets.',
    extra: ['jd', 'job-description'],
  },
  'dsh-headhunt': {
    niche: 'work & hiring',
    headline: 'Headhunter workbench',
    body: 'Outreach sequences, candidate pipelining, and engagement notes for agency recruiters - batch research on companies and roles, agent-drafted messages with human review.',
    extra: ['headhunt', 'recruiter', 'outreach'],
  },
  // ---- meta / product ----------------------------------------------------
  'dsh-global': {
    niche: 'meta / product',
    headline: 'The go-global toolkit for dsh',
    body: 'One install that presets every overseas lane - platform bridges, localization, and payment surfaces wired for the go-global playbook; the umbrella over the channel wall.',
    extra: ['global', 'channels'],
  },
  'dsh-registry': {
    niche: 'meta / product',
    headline: 'Local plugin registry',
    body: "An index of everything installed across profiles - plugins, presets, skills, with versions and provenance; the registry behind the hub panel. (Community stores and marketplaces ship separately.)",
    extra: ['registry', 'plugins', 'index'],
  },
  'dsh-hub': {
    niche: 'meta / product',
    headline: 'The plugin hub panel',
    body: "Browse, install, update, and remove harness extensions from the dsh web GUI - one view over every profile's inventory. Registered externally; promoted into the curated core.",
    extra: ['hub', 'plugins', 'panel'],
  },
  'dsh-studio': {
    niche: 'meta / product',
    headline: 'Studio shell for the DeepSeek Harness',
    body: 'Arrange sessions, workflows, and files in one persistent layout - the workbench around the conversation.',
    extra: [],
  },
  'dsh-hub': {
    niche: 'meta / product',
    headline: 'Local plugin hub for dsh installs',
    body: 'Your inventory, not a marketplace - installed plugins, their dependency graph, and one-click updates.',
    extra: [],
  },
  'dsh-forge': {
    niche: 'meta / product',
    headline: 'Scaffold new dsh plugins from templates',
    body: "Typed, tested, CI-wired plugin in one command - the generator this suite's own plugins were built with.",
    extra: ['scaffold', 'template'],
  },
  'dsh-canvas': {
    niche: 'meta / product',
    headline: 'Infinite canvas for the DeepSeek Harness',
    body: 'Pin conversation nodes, diffs, and notes spatially - thought work in two dimensions.',
    extra: [],
  },
  'dsh-suite': {
    niche: 'meta / product',
    headline: 'The full suite installer',
    body: 'Every plugin from this developer in one add - finder, git, diff, search, and the rest, pre-wired to agree with each other.',
    extra: [],
  },
  'dsh-workspace': {
    niche: 'meta / product',
    headline: 'Workspace manager for the DeepSeek Harness',
    body: 'Per-project personas, keymaps, and model pins that follow the directory you launch from.',
    extra: [],
  },
  'dsh-profiles': {
    niche: 'meta / product',
    headline: 'Profile manager for the DeepSeek Harness',
    body: 'Create, clone, switch, and inspect dsh profiles from the settings page, each with its own plugin manifest and patch layer.',
    extra: [],
  },
  'dsh-persona': {
    niche: 'meta / product',
    headline: 'Persona marketplace for the DeepSeek Harness',
    body: 'Install, switch, and pin agent personas (dsh-persona rows) from the GUI, with a community listing and per-profile overrides.',
    extra: ['persona'],
  },
  'dsh-skill': {
    niche: 'meta / product',
    headline: 'Skill manager for the DeepSeek Harness',
    body: 'Browse, install, enable, and pin agent skills from the settings page - catalogs, badges, and version pinning in one panel.',
    extra: ['skills'],
  },
  'dsh-update': {
    niche: 'meta / product',
    headline: 'Update manager for the DeepSeek Harness',
    body: 'Check and apply updates for dsh itself and every installed plugin from the GUI, with rollback from the backups each update leaves behind.',
    extra: [],
  },
  // ---- evaluation --------------------------------------------------------
  // Quality rails for agent output: judged runs, reproducible rubrics,
  // and edit coverage. (eval, bench, and score-spelled names already ship
  // as third-party community packages.)
  'dsh-judge': {
    niche: 'evaluation',
    headline: 'LLM-as-judge evaluation',
    body: 'Score agent output against a rubric with a second model pass - verdicts with per-criterion reasoning, disagreements flagged; pairs with dsh-council.',
    extra: ['judge', 'evaluation', 'llm-as-judge'],
  },
  'dsh-rubric': {
    niche: 'evaluation',
    headline: 'Scoring rubrics for agent work',
    body: 'Declarative rubric files - criteria, weights, pass thresholds - shared by dsh-judge and humans; the contract that makes evaluation reproducible.',
    extra: ['rubric', 'evaluation', 'scoring'],
  },
  'dsh-coverage': {
    niche: 'evaluation',
    headline: 'Agent edit coverage map',
    body: 'Which files, functions, and paths the agent actually touched - a coverage report for agent work, diffable run over run.',
    extra: ['coverage', 'report', 'diff'],
  },
  // ---- harness surfaces --------------------------------------------------
  'dsh-playbook': {
    niche: 'harness surfaces',
    headline: 'Playbook library for dsh',
    body: 'Named multi-step plays - incident response, release day, on-call handoff - one command runs the whole scripted sequence with checkpoints.',
    extra: ['playbook', 'ops'],
  },
  'dsh-runbook': {
    niche: 'harness surfaces',
    headline: 'Runbook runner for dsh',
    body: 'Executable runbooks - markdown checklists whose steps are agent actions; run them step-by-step with approval gates at the risky parts.',
    extra: ['runbook', 'ops'],
  },
  'dsh-sop': {
    niche: 'harness surfaces',
    headline: 'Standard operating procedures in the harness',
    body: 'SOPs as living documents - the agent knows the current procedure, proposes updates after incidents, and never improvises the critical path.',
    extra: ['sop', 'procedures'],
  },
  'dsh-macro': {
    niche: 'harness surfaces',
    headline: 'Macro recorder for agent actions',
    body: 'Record a sequence of agent actions once, replay it as one command with parameters - macros are prompt-level functions.',
    extra: ['macro', 'replay'],
  },
  'dsh-finder': {
    niche: 'harness surfaces',
    headline: 'File & command palette for the dsh web GUI',
    body: 'Fuzzy-find files in the workspace, jump between sessions, and invoke any slash command - Ctrl+P for the DeepSeek Harness web UI. Pairs with the Workflow Studio suite (dsh-workflow).',
    extra: [],
  },
  'dsh-notes': {
    niche: 'harness surfaces',
    headline: 'Durable notes the agent can see',
    body: 'A persistent scratchpad exposed as a model-facing tool and a sidebar panel - what the agent writes survives compaction and session switches.',
    extra: [],
  },
  'dsh-snippets': {
    niche: 'harness surfaces',
    headline: 'Prompt snippet library for the DeepSeek Harness',
    body: 'Reusable prompt fragments insertable into any session, stored as plain files so they stay versionable and shareable.',
    extra: [],
  },
  'dsh-prompts': {
    niche: 'harness surfaces',
    headline: 'Prompt library for the DeepSeek Harness',
    body: 'Versioned prompt templates attachable to any session or bot run - the fuller sibling of the snippet library.',
    extra: ['prompts', 'templates'],
  },
  'dsh-vscode': {
    niche: 'harness surfaces',
    headline: 'VS Code bridge for the DeepSeek Harness',
    body: 'Open the current workspace or session in VS Code, and drive dsh agents from the editor over the ACP stack.',
    extra: ['vscode'],
  },
  'dsh-zed': {
    niche: 'harness surfaces',
    headline: 'Zed bridge for the DeepSeek Harness',
    body: 'Drive dsh agents from Zed over the Agent Client Protocol - the editor-native counterpart to the VS Code bridge.',
    extra: ['zed', 'acp'],
  },
  'dsh-cursor': {
    niche: 'harness surfaces',
    headline: 'Cursor bridge for the DeepSeek Harness',
    body: 'Open dsh sessions and diffs in Cursor, and hand agent context to the editor - the third editor dock after VS Code and Zed.',
    extra: ['cursor'],
  },
  'dsh-i18n': {
    niche: 'harness surfaces',
    headline: 'Locale packs for the dsh web GUI',
    body: 'Community translations for the DeepSeek Harness web UI - zh, en, ja, and more - as drop-in packs with per-profile selection.',
    extra: ['i18n', 'locale'],
  },
  'dsh-l10n': {
    niche: 'harness surfaces',
    headline: 'Localization toolkit for dsh',
    body: 'The translation-and-adaptation lane - locale extraction, glossary consistency, and market-specific rewrites; the abbreviation the i18n world already speaks.',
    extra: ['l10n', 'localization'],
  },
  'dsh-keymap': {
    niche: 'harness surfaces',
    headline: 'Keyboard shortcut manager for the dsh web GUI',
    body: 'Custom chords, vim-mode presets, and importable keymaps for the DeepSeek Harness web UI.',
    extra: ['keymap'],
  },
  'dsh-completions': {
    niche: 'harness surfaces',
    headline: 'Shell completions for the dsh launcher',
    body: 'bash / zsh / fish completion recipes for the dsh CLI and plugin binaries like dsh-selfrepair.',
    extra: [],
  },
  // ---- protocols ----------------------------------------------------------
  'dsh-lsp': {
    niche: 'protocols',
    headline: 'Language Server Protocol bridge for the DeepSeek Harness',
    body: 'Diagnostics, hover, and go-to-definition from any language server, delivered to dsh agents and the web GUI - LSP as the editing interop seam, alongside MCP and A2A.',
    extra: ['lsp', 'language-server', 'protocol'],
  },
}

// External waves live in catalog-external.mjs (generated); merge them in so
// this file stays the hand-curated core and the union remains the catalog.
// Core wins on collision so promoted entries (e.g. dsh-swarm) are not
// shadowed by the generated external record.
export const CATALOG = { ...EXTERNAL, ...CORE }

// Packages with real shipped code - excluded from placeholder generation.
export const REAL_PACKAGES = ['dsh-selfrepair', 'dsh-workflow', 'dsh-bot']

export const PLACEHOLDER_VERSION = '0.0.1'
